// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.github.mcilloni.uplink.nano;

@SuppressWarnings("hiding")
public interface UplinkProto {

  // enum ErrCode
  public static final int EALREADYINVITED = 0;
  public static final int EEMPTYCONV = 1;
  public static final int ENAMEALREADYTAKEN = 2;
  public static final int ENOCONV = 3;
  public static final int ENOUSER = 4;
  public static final int ENOTINVITED = 5;
  public static final int ENOTMEMBER = 6;
  public static final int ESELFINVITE = 7;
  public static final int ESERVERFAULT = 8;
  public static final int EBROKEPROTO = 9;
  public static final int EAUTHFAIL = 10;

  public static final class ErrCodeResp extends
      com.google.protobuf.nano.MessageNano {
    public static final int SUCCESS_FIELD_NUMBER = 1;
    public static final int ERR_CODE_FIELD_NUMBER = 2;
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public int getResponseCase() {
      return this.responseCase_;
    }
    public ErrCodeResp clearResponse() {
      this.responseCase_ = 0;
      this.response_ = null;
      return this;
    }

    private static volatile ErrCodeResp[] _emptyArray;
    public static ErrCodeResp[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ErrCodeResp[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool success = 1;
    public boolean hasSuccess() {
      return this.responseCase_ == 1;
    }
    public boolean getSuccess() {
      if (this.responseCase_ == 1) {
        return (boolean) (java.lang.Boolean) this.response_;
      }
      return false;
    }
    public ErrCodeResp setSuccess(boolean value) {
      this.responseCase_ = 1;
      this.response_ = value;
      return this;
    }

    // optional .protodef.ErrCode err_code = 2;
    public boolean hasErrCode() {
      return this.responseCase_ == 2;
    }
    public int getErrCode() {
      if (this.responseCase_ == 2) {
        return (int) (java.lang.Integer) this.response_;
      }
      return com.github.mcilloni.uplink.nano.UplinkProto.EALREADYINVITED;
    }
    public ErrCodeResp setErrCode(int value) {
      this.responseCase_ = 2;
      this.response_ = value;
      return this;
    }

    public ErrCodeResp() {
      clear();
    }

    public ErrCodeResp clear() {
      clearResponse();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.responseCase_ == 1) {
        output.writeBool(
            1, (java.lang.Boolean) this.response_);
      }
      if (this.responseCase_ == 2) {
        output.writeEnum(
            2, (java.lang.Integer) this.response_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.responseCase_ == 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(
                1, (java.lang.Boolean) this.response_);
      }
      if (this.responseCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeEnumSize(
                2, (java.lang.Integer) this.response_);
      }
      return size;
    }

    @Override
    public ErrCodeResp mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.response_ = input.readBool();
            this.responseCase_ = 1;
            break;
          }
          case 16: {
            this.response_ = input.readEnum();
            this.responseCase_ = 2;
            break;
          }
        }
      }
    }

    public static ErrCodeResp parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ErrCodeResp(), data);
    }

    public static ErrCodeResp parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ErrCodeResp().mergeFrom(input);
    }
  }

  public static final class NewUserReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile NewUserReq[] _emptyArray;
    public static NewUserReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new NewUserReq[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string name = 1;
    public java.lang.String name;

    // optional bytes public_key = 2;
    public byte[] publicKey;

    // optional bytes enc_private_key = 3;
    public byte[] encPrivateKey;

    // optional string ch_token = 4;
    public java.lang.String chToken;

    // optional bytes enc_ch_token = 5;
    public byte[] encChToken;

    public NewUserReq() {
      clear();
    }

    public NewUserReq clear() {
      name = "";
      publicKey = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      encPrivateKey = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      chToken = "";
      encChToken = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.name.equals("")) {
        output.writeString(1, this.name);
      }
      if (!java.util.Arrays.equals(this.publicKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.publicKey);
      }
      if (!java.util.Arrays.equals(this.encPrivateKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(3, this.encPrivateKey);
      }
      if (!this.chToken.equals("")) {
        output.writeString(4, this.chToken);
      }
      if (!java.util.Arrays.equals(this.encChToken, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(5, this.encChToken);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.name);
      }
      if (!java.util.Arrays.equals(this.publicKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.publicKey);
      }
      if (!java.util.Arrays.equals(this.encPrivateKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.encPrivateKey);
      }
      if (!this.chToken.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.chToken);
      }
      if (!java.util.Arrays.equals(this.encChToken, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(5, this.encChToken);
      }
      return size;
    }

    @Override
    public NewUserReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.name = input.readString();
            break;
          }
          case 18: {
            this.publicKey = input.readBytes();
            break;
          }
          case 26: {
            this.encPrivateKey = input.readBytes();
            break;
          }
          case 34: {
            this.chToken = input.readString();
            break;
          }
          case 42: {
            this.encChToken = input.readBytes();
            break;
          }
        }
      }
    }

    public static NewUserReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new NewUserReq(), data);
    }

    public static NewUserReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new NewUserReq().mergeFrom(input);
    }
  }

  public static final class NewUserResp extends
      com.google.protobuf.nano.MessageNano {
    public static final int SESSION_INFO_FIELD_NUMBER = 1;
    public static final int ERR_CODE_FIELD_NUMBER = 2;
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public int getResponseCase() {
      return this.responseCase_;
    }
    public NewUserResp clearResponse() {
      this.responseCase_ = 0;
      this.response_ = null;
      return this;
    }

    private static volatile NewUserResp[] _emptyArray;
    public static NewUserResp[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new NewUserResp[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .protodef.SessInfo session_info = 1;
    public boolean hasSessionInfo() {
      return this.responseCase_ == 1;
    }
    public com.github.mcilloni.uplink.nano.UplinkProto.SessInfo getSessionInfo() {
      if (this.responseCase_ == 1) {
        return (com.github.mcilloni.uplink.nano.UplinkProto.SessInfo) this.response_;
      }
      return null;
    }
    public NewUserResp setSessionInfo(com.github.mcilloni.uplink.nano.UplinkProto.SessInfo value) {
      if (value == null) { throw new java.lang.NullPointerException(); }
      this.responseCase_ = 1;
      this.response_ = value;
      return this;
    }

    // optional .protodef.ErrCode err_code = 2;
    public boolean hasErrCode() {
      return this.responseCase_ == 2;
    }
    public int getErrCode() {
      if (this.responseCase_ == 2) {
        return (int) (java.lang.Integer) this.response_;
      }
      return com.github.mcilloni.uplink.nano.UplinkProto.EALREADYINVITED;
    }
    public NewUserResp setErrCode(int value) {
      this.responseCase_ = 2;
      this.response_ = value;
      return this;
    }

    public NewUserResp() {
      clear();
    }

    public NewUserResp clear() {
      clearResponse();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.responseCase_ == 1) {
        output.writeMessage(1,
            (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 2) {
        output.writeEnum(
            2, (java.lang.Integer) this.response_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.responseCase_ == 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1,
              (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeEnumSize(
                2, (java.lang.Integer) this.response_);
      }
      return size;
    }

    @Override
    public NewUserResp mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (!(this.responseCase_ == 1)) {
              this.response_ = new com.github.mcilloni.uplink.nano.UplinkProto.SessInfo();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.response_);
            this.responseCase_ = 1;
            break;
          }
          case 16: {
            this.response_ = input.readEnum();
            this.responseCase_ = 2;
            break;
          }
        }
      }
    }

    public static NewUserResp parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new NewUserResp(), data);
    }

    public static NewUserResp parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new NewUserResp().mergeFrom(input);
    }
  }

  public static final class LoginReq extends
      com.google.protobuf.nano.MessageNano {
    public static final int STEP1_FIELD_NUMBER = 1;
    public static final int STEP2_FIELD_NUMBER = 2;
    public static final int STEP3_FIELD_NUMBER = 3;
    private int loginStepsCase_ = 0;
    private java.lang.Object loginSteps_;
    public int getLoginStepsCase() {
      return this.loginStepsCase_;
    }
    public LoginReq clearLoginSteps() {
      this.loginStepsCase_ = 0;
      this.loginSteps_ = null;
      return this;
    }

    private static volatile LoginReq[] _emptyArray;
    public static LoginReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LoginReq[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .protodef.Username step1 = 1;
    public boolean hasStep1() {
      return this.loginStepsCase_ == 1;
    }
    public com.github.mcilloni.uplink.nano.UplinkProto.Username getStep1() {
      if (this.loginStepsCase_ == 1) {
        return (com.github.mcilloni.uplink.nano.UplinkProto.Username) this.loginSteps_;
      }
      return null;
    }
    public LoginReq setStep1(com.github.mcilloni.uplink.nano.UplinkProto.Username value) {
      if (value == null) { throw new java.lang.NullPointerException(); }
      this.loginStepsCase_ = 1;
      this.loginSteps_ = value;
      return this;
    }

    // optional .protodef.FirstChallenge step2 = 2;
    public boolean hasStep2() {
      return this.loginStepsCase_ == 2;
    }
    public com.github.mcilloni.uplink.nano.UplinkProto.FirstChallenge getStep2() {
      if (this.loginStepsCase_ == 2) {
        return (com.github.mcilloni.uplink.nano.UplinkProto.FirstChallenge) this.loginSteps_;
      }
      return null;
    }
    public LoginReq setStep2(com.github.mcilloni.uplink.nano.UplinkProto.FirstChallenge value) {
      if (value == null) { throw new java.lang.NullPointerException(); }
      this.loginStepsCase_ = 2;
      this.loginSteps_ = value;
      return this;
    }

    // optional .protodef.SecondChallenge step3 = 3;
    public boolean hasStep3() {
      return this.loginStepsCase_ == 3;
    }
    public com.github.mcilloni.uplink.nano.UplinkProto.SecondChallenge getStep3() {
      if (this.loginStepsCase_ == 3) {
        return (com.github.mcilloni.uplink.nano.UplinkProto.SecondChallenge) this.loginSteps_;
      }
      return null;
    }
    public LoginReq setStep3(com.github.mcilloni.uplink.nano.UplinkProto.SecondChallenge value) {
      if (value == null) { throw new java.lang.NullPointerException(); }
      this.loginStepsCase_ = 3;
      this.loginSteps_ = value;
      return this;
    }

    public LoginReq() {
      clear();
    }

    public LoginReq clear() {
      clearLoginSteps();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.loginStepsCase_ == 1) {
        output.writeMessage(1,
            (com.google.protobuf.nano.MessageNano) this.loginSteps_);
      }
      if (this.loginStepsCase_ == 2) {
        output.writeMessage(2,
            (com.google.protobuf.nano.MessageNano) this.loginSteps_);
      }
      if (this.loginStepsCase_ == 3) {
        output.writeMessage(3,
            (com.google.protobuf.nano.MessageNano) this.loginSteps_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.loginStepsCase_ == 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1,
              (com.google.protobuf.nano.MessageNano) this.loginSteps_);
      }
      if (this.loginStepsCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2,
              (com.google.protobuf.nano.MessageNano) this.loginSteps_);
      }
      if (this.loginStepsCase_ == 3) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3,
              (com.google.protobuf.nano.MessageNano) this.loginSteps_);
      }
      return size;
    }

    @Override
    public LoginReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (!(this.loginStepsCase_ == 1)) {
              this.loginSteps_ = new com.github.mcilloni.uplink.nano.UplinkProto.Username();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.loginSteps_);
            this.loginStepsCase_ = 1;
            break;
          }
          case 18: {
            if (!(this.loginStepsCase_ == 2)) {
              this.loginSteps_ = new com.github.mcilloni.uplink.nano.UplinkProto.FirstChallenge();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.loginSteps_);
            this.loginStepsCase_ = 2;
            break;
          }
          case 26: {
            if (!(this.loginStepsCase_ == 3)) {
              this.loginSteps_ = new com.github.mcilloni.uplink.nano.UplinkProto.SecondChallenge();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.loginSteps_);
            this.loginStepsCase_ = 3;
            break;
          }
        }
      }
    }

    public static LoginReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LoginReq(), data);
    }

    public static LoginReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LoginReq().mergeFrom(input);
    }
  }

  public static final class Username extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Username[] _emptyArray;
    public static Username[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Username[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string name = 1;
    public java.lang.String name;

    public Username() {
      clear();
    }

    public Username clear() {
      name = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.name.equals("")) {
        output.writeString(1, this.name);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.name);
      }
      return size;
    }

    @Override
    public Username mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.name = input.readString();
            break;
          }
        }
      }
    }

    public static Username parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Username(), data);
    }

    public static Username parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Username().mergeFrom(input);
    }
  }

  public static final class FirstChallenge extends
      com.google.protobuf.nano.MessageNano {

    private static volatile FirstChallenge[] _emptyArray;
    public static FirstChallenge[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new FirstChallenge[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bytes enc_ch_token = 1;
    public byte[] encChToken;

    public FirstChallenge() {
      clear();
    }

    public FirstChallenge clear() {
      encChToken = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.encChToken, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.encChToken);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.encChToken, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.encChToken);
      }
      return size;
    }

    @Override
    public FirstChallenge mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.encChToken = input.readBytes();
            break;
          }
        }
      }
    }

    public static FirstChallenge parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new FirstChallenge(), data);
    }

    public static FirstChallenge parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new FirstChallenge().mergeFrom(input);
    }
  }

  public static final class SecondChallenge extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SecondChallenge[] _emptyArray;
    public static SecondChallenge[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SecondChallenge[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bytes final_challenge = 1;
    public byte[] finalChallenge;

    public SecondChallenge() {
      clear();
    }

    public SecondChallenge clear() {
      finalChallenge = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.finalChallenge, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.finalChallenge);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.finalChallenge, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.finalChallenge);
      }
      return size;
    }

    @Override
    public SecondChallenge mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.finalChallenge = input.readBytes();
            break;
          }
        }
      }
    }

    public static SecondChallenge parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SecondChallenge(), data);
    }

    public static SecondChallenge parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SecondChallenge().mergeFrom(input);
    }
  }

  public static final class LoginResp extends
      com.google.protobuf.nano.MessageNano {
    public static final int STEP1_FIELD_NUMBER = 1;
    public static final int STEP2_FIELD_NUMBER = 2;
    public static final int STEP3_FIELD_NUMBER = 3;
    public static final int ERR_CODE_FIELD_NUMBER = 4;
    private int loginStepsCase_ = 0;
    private java.lang.Object loginSteps_;
    public int getLoginStepsCase() {
      return this.loginStepsCase_;
    }
    public LoginResp clearLoginSteps() {
      this.loginStepsCase_ = 0;
      this.loginSteps_ = null;
      return this;
    }

    private static volatile LoginResp[] _emptyArray;
    public static LoginResp[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LoginResp[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string step1 = 1;
    public boolean hasStep1() {
      return this.loginStepsCase_ == 1;
    }
    public java.lang.String getStep1() {
      if (this.loginStepsCase_ == 1) {
        return (java.lang.String) (java.lang.String) this.loginSteps_;
      }
      return "";
    }
    public LoginResp setStep1(java.lang.String value) {
      this.loginStepsCase_ = 1;
      this.loginSteps_ = value;
      return this;
    }

    // optional .protodef.UserInfo step2 = 2;
    public boolean hasStep2() {
      return this.loginStepsCase_ == 2;
    }
    public com.github.mcilloni.uplink.nano.UplinkProto.UserInfo getStep2() {
      if (this.loginStepsCase_ == 2) {
        return (com.github.mcilloni.uplink.nano.UplinkProto.UserInfo) this.loginSteps_;
      }
      return null;
    }
    public LoginResp setStep2(com.github.mcilloni.uplink.nano.UplinkProto.UserInfo value) {
      if (value == null) { throw new java.lang.NullPointerException(); }
      this.loginStepsCase_ = 2;
      this.loginSteps_ = value;
      return this;
    }

    // optional .protodef.SessInfo step3 = 3;
    public boolean hasStep3() {
      return this.loginStepsCase_ == 3;
    }
    public com.github.mcilloni.uplink.nano.UplinkProto.SessInfo getStep3() {
      if (this.loginStepsCase_ == 3) {
        return (com.github.mcilloni.uplink.nano.UplinkProto.SessInfo) this.loginSteps_;
      }
      return null;
    }
    public LoginResp setStep3(com.github.mcilloni.uplink.nano.UplinkProto.SessInfo value) {
      if (value == null) { throw new java.lang.NullPointerException(); }
      this.loginStepsCase_ = 3;
      this.loginSteps_ = value;
      return this;
    }

    // optional .protodef.ErrCode err_code = 4;
    public boolean hasErrCode() {
      return this.loginStepsCase_ == 4;
    }
    public int getErrCode() {
      if (this.loginStepsCase_ == 4) {
        return (int) (java.lang.Integer) this.loginSteps_;
      }
      return com.github.mcilloni.uplink.nano.UplinkProto.EALREADYINVITED;
    }
    public LoginResp setErrCode(int value) {
      this.loginStepsCase_ = 4;
      this.loginSteps_ = value;
      return this;
    }

    public LoginResp() {
      clear();
    }

    public LoginResp clear() {
      clearLoginSteps();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.loginStepsCase_ == 1) {
        output.writeString(
            1, (java.lang.String) this.loginSteps_);
      }
      if (this.loginStepsCase_ == 2) {
        output.writeMessage(2,
            (com.google.protobuf.nano.MessageNano) this.loginSteps_);
      }
      if (this.loginStepsCase_ == 3) {
        output.writeMessage(3,
            (com.google.protobuf.nano.MessageNano) this.loginSteps_);
      }
      if (this.loginStepsCase_ == 4) {
        output.writeEnum(
            4, (java.lang.Integer) this.loginSteps_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.loginStepsCase_ == 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(
                1, (java.lang.String) this.loginSteps_);
      }
      if (this.loginStepsCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2,
              (com.google.protobuf.nano.MessageNano) this.loginSteps_);
      }
      if (this.loginStepsCase_ == 3) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3,
              (com.google.protobuf.nano.MessageNano) this.loginSteps_);
      }
      if (this.loginStepsCase_ == 4) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeEnumSize(
                4, (java.lang.Integer) this.loginSteps_);
      }
      return size;
    }

    @Override
    public LoginResp mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.loginSteps_ = input.readString();
            this.loginStepsCase_ = 1;
            break;
          }
          case 18: {
            if (!(this.loginStepsCase_ == 2)) {
              this.loginSteps_ = new com.github.mcilloni.uplink.nano.UplinkProto.UserInfo();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.loginSteps_);
            this.loginStepsCase_ = 2;
            break;
          }
          case 26: {
            if (!(this.loginStepsCase_ == 3)) {
              this.loginSteps_ = new com.github.mcilloni.uplink.nano.UplinkProto.SessInfo();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.loginSteps_);
            this.loginStepsCase_ = 3;
            break;
          }
          case 32: {
            this.loginSteps_ = input.readEnum();
            this.loginStepsCase_ = 4;
            break;
          }
        }
      }
    }

    public static LoginResp parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LoginResp(), data);
    }

    public static LoginResp parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LoginResp().mergeFrom(input);
    }
  }

  public static final class UserInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile UserInfo[] _emptyArray;
    public static UserInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UserInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bytes public_key = 1;
    public byte[] publicKey;

    // optional bytes enc_private_key = 2;
    public byte[] encPrivateKey;

    // optional bytes enc_ch_token = 3;
    public byte[] encChToken;

    public UserInfo() {
      clear();
    }

    public UserInfo clear() {
      publicKey = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      encPrivateKey = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      encChToken = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.publicKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.publicKey);
      }
      if (!java.util.Arrays.equals(this.encPrivateKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.encPrivateKey);
      }
      if (!java.util.Arrays.equals(this.encChToken, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(3, this.encChToken);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.publicKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.publicKey);
      }
      if (!java.util.Arrays.equals(this.encPrivateKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.encPrivateKey);
      }
      if (!java.util.Arrays.equals(this.encChToken, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.encChToken);
      }
      return size;
    }

    @Override
    public UserInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.publicKey = input.readBytes();
            break;
          }
          case 18: {
            this.encPrivateKey = input.readBytes();
            break;
          }
          case 26: {
            this.encChToken = input.readBytes();
            break;
          }
        }
      }
    }

    public static UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UserInfo(), data);
    }

    public static UserInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UserInfo().mergeFrom(input);
    }
  }

  public static final class SessInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SessInfo[] _emptyArray;
    public static SessInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SessInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 uid = 1;
    public long uid;

    // optional string session_id = 2;
    public java.lang.String sessionId;

    public SessInfo() {
      clear();
    }

    public SessInfo clear() {
      uid = 0L;
      sessionId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uid != 0L) {
        output.writeInt64(1, this.uid);
      }
      if (!this.sessionId.equals("")) {
        output.writeString(2, this.sessionId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.uid);
      }
      if (!this.sessionId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.sessionId);
      }
      return size;
    }

    @Override
    public SessInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uid = input.readInt64();
            break;
          }
          case 18: {
            this.sessionId = input.readString();
            break;
          }
        }
      }
    }

    public static SessInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SessInfo(), data);
    }

    public static SessInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SessInfo().mergeFrom(input);
    }
  }
}
